
--MODULE2--
--JOINS--

select * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

--1--
SELECT  EMP.DEPTNO,ENAME, DNAME FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

--2--
--INSUFFICEINT DATA IN EMP TABLE

--3--
SELECT ENAME, DNAME, GRADE FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO INNER JOIN SALGRADE ON EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL;

--4--
SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE DNAME='RESEARCH'; 

--5--
SELECT * FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

--6--
SELECT * FROM EMP RIGHT OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

--7--
SELECT * FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

--8--
--TABLE DO NOT CONTAINS MANAGER NAME COLUMN--



--DDL--
--1--
CREATE TABLE DEPARTMENT_2251
(
  DNAME VARCHAR2(20 BYTE),
  DEPTNO NUMBER(10,0) NOT NULL,
  LOCATION VARCHAR2(30 BYTE)
)
--2--
CREATE TABLE EMPLOYEE_2251 
(
  EMPNO NUMBER(10, 0) NOT NULL 
, ENAME VARCHAR2(20 BYTE) NOT NULL 
, DESIGNATION VARCHAR2(30 BYTE) 
, SEX VARCHAR2(6 BYTE) 
, BASIC_SALARY NUMBER(6, 0) 
, DATE_OF_JOINING DATE 
, DEPTNO NUMBER 
, CONSTRAINT SYS_C00302267 PRIMARY KEY 
  (
    EMPNO 
  )
)

--3--
ALTER TABLE EMPLOYEE_2251
ADD COMMISSION NUMBER(10,0);

--4--
CREATE INDEX EMPI 
ON EMPLOYEE_2251(ENMAE);

--5--
SELECT * INTO EMPCOPY
FROM EMPLYOEE_2251
WHERE 1=2;

--7--
DROP INDEX EMPLOYEE_2251.EMPI;

SELECT * FROM EMPLOYEE_2251;
SELECT * FROM DEPARTMENT_2251;

--DML--
--1--
INSERT INTO DEPARTMENT_2251(DEPTNO,DNAME,LOCATION)
VALUES(10,'ENGINEER','HYDERABAD');
INSERT INTO DEPARTMENT_2251(DEPTNO,DNAME,LOCATION)
VALUES(20,'MANAGER','BANGLORE');
INSERT INTO DEPARTMENT_2251(DEPTNO,DNAME,LOCATION)
VALUES(30,'SENIOR','DELHI');


--2--
INSERT INTO EMPLOYEE_2251( EMPNO, ENAME, DESIGNATION,SEX, BASIC_SALARY,DATE_OF_JOINING,DEPTNO,COMMISSION)
VALUES(1,'HIMANSHU','SOFTWARE','MALE',40000,'23/7/19',10,1000);
INSERT INTO EMPLOYEE_2251( EMPNO, ENAME, DESIGNATION,SEX, BASIC_SALARY,DATE_OF_JOINING,DEPTNO,COMMISSION)
VALUES(2,'SUYASH','MANAGER','MALE',60000,'24/7/19',20,5000);
INSERT INTO EMPLOYEE_2251( EMPNO, ENAME, DESIGNATION,SEX, BASIC_SALARY,DATE_OF_JOINING,DEPTNO,COMMISSION)
VALUES(3,'TUSHAR','SENIOR SOFTWARE','MALE',90000,'25/7/19',30,10000);
INSERT INTO EMPLOYEE_2251( EMPNO, ENAME, DESIGNATION,SEX, BASIC_SALARY,DATE_OF_JOINING,DEPTNO,COMMISSION)
VALUES (4,'SHWETIMA','MANAGER','FEMALE',60000,'24/7/19',20,5000);
INSERT INTO EMPLOYEE_2251( EMPNO, ENAME, DESIGNATION,SEX, BASIC_SALARY,DATE_OF_JOINING,DEPTNO,COMMISSION)
VALUES (5,'VIKESH','MANAGER','MALE',60000,'24/7/19',20,5000);
INSERT INTO EMPLOYEE_2251( EMPNO, ENAME, DESIGNATION,SEX, BASIC_SALARY,DATE_OF_JOINING,DEPTNO,COMMISSION)
VALUES (6,'SWATI','SOFTWARE','FEMALE',30000,'26/7/19',30,1000);
--SELECT * FROM EMPLOYEE_2251;

--3--
UPDATE EMPLOYEE_2251
SET BASIC_SALARY = BASIC_SALARY +  (BASIC_SALARY*0.1)
WHERE DEPTNO=10;

--4--
UPDATE EMPLOYEE_2251
SET BASIC_SALARY= BASIC_SALARY + 0.1*BASIC_SALARY,
COMMISSION= COMMISSION+0.02*COMMISSION
WHERE COMMISSION >=5000;

--5--
UPDATE EMPLOYEE_2251
SET DESIGNATION='MANAGER'
WHERE EMPNO=3;

--6--
DELETE FROM EMPLOYEE_2251
WHERE DATE_OF_JOINING < '24-07-19';


SAVEPOINT ABC;
--7--
DELETE FROM EMPLOYEE_2251;

--8--
SELECT * FROM EMPLOYEE_2251;

--9--
ROLLBACK TO ABC;


--10--
SELECT * FROM EMPLOYEE_2251;

--11--
TRUNCATE TABLE EMPLOYEE_2251;

--PROCEDURE AND FUNCTIONS--
SELECT * FROM SALGRADE;
SELECT *FROM EMP;
--1--

CREATE OR REPLACE PROCEDURE DISP_EMP_DETAILS_2251
(
IEMPNO IN EMP.EMPNO%TYPE,
SGRADE OUT SALGRADE.GRADE%TYPE,
SSALARY OUT EMP.SAL%TYPE)
AS
BEGIN
SELECT DISTINCT GRADE, SAL INTO SGRADE, SSALARY FROM EMP INNER JOIN SALGRADE ON (EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL) WHERE EMPNO=IEMPNO;
END;


SET SERVEROUTPUT ON;
DECLARE
SGRADE SALGRADE.GRADE%TYPE;
SSALARY EMP.SAL%TYPE;
BEGIN
DISP_EMP_DETAILS_2251(7902,SGRADE,SSALARY);
DBMS_OUTPUT.PUT_LINE('GRADE:'||SGRADE);
DBMS_OUTPUT.PUT_LINE('SALARY:'||SSALARY);
END; 


--2--
CREATE OR REPLACE PROCEDURE DISPLAY_RECORDS_2251(P_JOB EMP.JOB%TYPE)
AS 
BEGIN

FOR REC IN(
SELECT EMPNO,SAL,DEPTNO,JOB FROM EMP WHERE JOB=P_JOB)
LOOP
DBMS_OUTPUT.PUT('EMPNO:' || REC.EMPNO);
DBMS_OUTPUT.PUT('SALARY:' || REC.SAL);
DBMS_OUTPUT.PUT('DEPTNO:' || REC.DEPTNO);
DBMS_OUTPUT.PUT('JOB:' || REC.JOB);
DBMS_OUTPUT.PUT_LINE('');
END LOOP;
END;

SET SERVEROUTPUT ON;
BEGIN
hr.DISPLAY_RECORDS_2251('CLERK');
END;

--3--
CREATE OR REPLACE FUNCTION GET_EMP_ANNUAL (IEMPNO EMP.EMPNO%TYPE)
RETURN NUMBER IS
ANNUAL_SALARY NUMBER(10,0):=0;
BEGIN
SELECT SAL*12 INTO ANNUAL_SALARY
FROM EMP
WHERE EMPNO=IEMPNO;
RETURN ANNUAL_SALARY;
END;

SET SERVEROUTPUT ON;
DECLARE
C NUMBER(10,0);
BEGIN
C:= GET_EMP_ANNUAL(7900);
DBMS_OUTPUT.PUT_LINE('ANNUAL SALARY:' || C);
END;

