--Module 1
--select statement
--1--
select table_name from user_tables;
select table_name from user_tables where table_name='DEPT' or table_name='EMP' or table_name='SALGRADE';

--2--
create table SALGRADE(
GRADE NUMBER,
HISAL NUMBER,
LOSAL NUMBER);

INSERT INTO SALGRADE VALUES (1,700,1200);
INSERT INTO SALGRADE VALUES (2,1201,1400);
INSERT INTO SALGRADE VALUES (3,1401,2000);
INSERT INTO SALGRADE VALUES (4,2001,3000);
INSERT INTO SALGRADE VALUES (5,3001,9999);

--3--
SELECT * FROM DEPT;

--4--
SELECT* FROM EMP;

--5--
SELECT* FROM SALGRADE;

--6--
SELECT EMPNO,ENAME,SAL FROM EMP;

--7--
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL>3000;

--8--


--9--
SELECT * FROM EMP WHERE JOB='CLERK';

--10--
SELECT * FROM EMP ORDER BY SAL ASC ;

--11--
SELECT * FROM EMP ORDER BY DEPTNO DESC,JOB ASC;

--12--
SELECT DISTINCT DNAME FROM DEPT, EMP WHERE EMP.DEPTNO=DEPT.DEPTNO;

--13--
SELECT DISTINCT DNAME,JOB FROM DEPT,EMP WHERE EMP.DEPTNO=DEPT.DEPTNO ORDER BY DNAME;

--14--
SELECT ENAME, SAL, 12* SAL AS ANNUAL_SALARY  FROM EMP ORDER BY ANNUAL_SALARY DESC;

--15--
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;

--16--
SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO!=10 AND DEPTNO!= 20;

--17--
SELECT * FROM EMP WHERE JOB!='SALESMAN';

--18--
SELECT * FROM EMP WHERE JOB='SALESMAN';

--19--
SELECT * FROM EMP ORDER BY CASE WHEN COMM IS NULL THEN 0 ELSE 1 END,COMM ASC;

--20--
SELECT * FROM EMP WHERE ENAME='SMITH';

--21--
SELECT * FROM EMP WHERE ENAME LIKE '%MI%';

--22--
SELECT * FROM EMP WHERE ENAME LIKE '_%';

--23--


--24--
SELECT * FROM EMP WHERE JOB='CLERK' AND DEPTNO=10;


--25--
SELECT SUM(SAL),MAX(SAL),MIN(SAL), AVG(SAL) FROM EMP;

--26--
SELECT AVG(COMM), COUNT(COMM) FROM EMP WHERE DEPTNO=10;

--27--
SELECT DNAME, COUNT(ENAME), SUM(SAL) FROM DEPT, EMP WHERE EMP.DEPTNO=DEPT.DEPTNO GROUP BY DNAME;


--28--
SELECT  JOB, SUM(SAL) FROM DEPT, EMP WHERE EMP.DEPTNO=DEPT.DEPTNO GROUP BY JOB; 

--29--
SELECT DNAME, SUM(SAL) FROM DEPT, EMP WHERE DEPT.DEPTNO=EMP.DEPTNO AND (DEPT.DEPTNO=10 OR DEPT.DEPTNO=20) GROUP BY DNAME;

--30--
WITH CTA AS(
SELECT DNAME, SUM(SAL)AS TOTAL FROM DEPT, EMP WHERE ( DEPT.DEPTNO=EMP.DEPTNO ) GROUP BY DNAME)
SELECT * FROM CTA WHERE CTA.TOTAL>6000;

--31--
SELECT COUNT(*), COUNT(COMM) FROM EMP;
--BOTH COUNT ARE DIFFERENT BECAUSE COMM COLUMN HAS NULL VALUES--

--SUB QUERIES--
--1--
SELECT ENAME FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME='SMITH');

--2--


--3--
SELECT ENAME FROM EMP WHERE SAL IN (SELECT SAL FROM EMP WHERE ENAME='SCOTT');

--4--
SELECT DISTINCT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP);

--5--
SELECT ENAME FROM EMP WHERE SAL >=( SELECT MAX(SAL) FROM EMP WHERE DEPTNO=20);

--6--
WITH ABC AS (SELECT DEPTNO, JOB FROM EMP WHERE EMPNO=7788)
SELECT * FROM EMP, ABC WHERE EMP.DEPTNO=ABC.DEPTNO AND EMP.JOB=ABC.JOB ;

--7--
SELECT * FROM EMP WHERE JOB!='MANAGER';

--8--
SELECT * FROM EMP WHERE JOB='MANAGER';

--9--
WITH  ABD AS
(SELECT DNAME,AVG(SAL) AS AVERAGE FROM DEPT, EMP WHERE DEPT.DEPTNO=EMP.DEPTNO GROUP BY DNAME)
SELECT DEPT.DNAME,ENAME FROM EMP,ABD,DEPT WHERE EMP.SAL>ABD.AVERAGE AND DEPT.DNAME=ABD.DNAME;

--11--
SELECT DISTINCT DNAME FROM DEPT WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMP);

